### ISSUE TITLE
Fallo al editar una reunión

### ISSUE THREAD

**Issue by ferherque** [drorganvidez/evidentia#106]
Cuando se intentan editar los campos tipo/modalidad dentro de una reunión ya creada y se confirman los cambios, las modificaciones no se guardan.
Además, en el formulario los valores que salen por defecto al editar siempre son "Presencial" y "Ordinario" (los primeros valores) en lugar de los que hay guardados en la base de datos.

**Comment by drorganvidez** [comment]
Mergeado, ¡gracias!
